# Generated by Django 5.2.15 on 2026-06-16 15:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The calendar date for this log')),
                ('day_number', models.IntegerField(help_text='Day number within the trip (1-based)')),
                ('total_miles_driving', models.FloatField(default=0, help_text='Miles driven on this day')),
                ('total_hours_driving', models.FloatField(default=0, help_text='Hours spent driving on this day')),
                ('total_hours_on_duty', models.FloatField(default=0, help_text='Hours spent on-duty (not driving) on this day')),
                ('total_hours_off_duty', models.FloatField(default=0, help_text='Hours spent off-duty on this day')),
                ('total_hours_sleeper', models.FloatField(default=0, help_text='Hours spent in sleeper berth on this day')),
                ('from_location', models.CharField(blank=True, help_text='Starting location for this day', max_length=255)),
                ('to_location', models.CharField(blank=True, help_text='Ending location for this day', max_length=255)),
                ('cycle_hours_available', models.FloatField(default=70, help_text='Hours available in the 70-hr/8-day cycle at start of day')),
            ],
            options={
                'verbose_name': 'Daily Log',
                'verbose_name_plural': 'Daily Logs',
                'ordering': ['trip', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(help_text="Driver's current location (address or city, state)", max_length=255)),
                ('current_lat', models.FloatField(help_text='Current location latitude')),
                ('current_lng', models.FloatField(help_text='Current location longitude')),
                ('pickup_location', models.CharField(help_text='Cargo pickup location', max_length=255)),
                ('pickup_lat', models.FloatField(help_text='Pickup latitude')),
                ('pickup_lng', models.FloatField(help_text='Pickup longitude')),
                ('dropoff_location', models.CharField(help_text='Cargo dropoff location', max_length=255)),
                ('dropoff_lat', models.FloatField(help_text='Dropoff latitude')),
                ('dropoff_lng', models.FloatField(help_text='Dropoff longitude')),
                ('current_cycle_used', models.FloatField(help_text='Hours already used in the 70-hr/8-day cycle', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_distance', models.FloatField(blank=True, help_text='Total trip distance in miles', null=True)),
                ('total_duration', models.FloatField(blank=True, help_text='Total estimated trip duration in hours (including stops)', null=True)),
                ('total_driving_hours', models.FloatField(blank=True, help_text='Total driving time in hours', null=True)),
                ('total_days', models.IntegerField(blank=True, help_text='Number of days the trip spans', null=True)),
                ('route_geometry', models.JSONField(blank=True, help_text='Encoded route polyline coordinates for map rendering', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyStatusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=20)),
                ('start_time', models.FloatField(help_text='Start hour of this status (0.0 = midnight, 12.0 = noon)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('end_time', models.FloatField(help_text='End hour of this status', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('location', models.CharField(blank=True, help_text='Location where this status change occurred', max_length=255)),
                ('remarks', models.CharField(blank=True, help_text="Remarks for this duty period (e.g., 'Pre-trip inspection')", max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trips.dailylog')),
            ],
            options={
                'verbose_name': 'Duty Status Entry',
                'verbose_name_plural': 'Duty Status Entries',
                'ordering': ['daily_log', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('start', 'Start Location'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel Stop'), ('rest', 'Rest Stop (10-hr off-duty)'), ('break', '30-Min Break')], max_length=20)),
                ('location_name', models.CharField(help_text='City, State or descriptive name of the stop location', max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('arrival_time', models.DateTimeField(help_text='When the driver arrives at this stop')),
                ('departure_time', models.DateTimeField(help_text='When the driver departs from this stop')),
                ('duration_hours', models.FloatField(help_text='Duration of the stop in hours')),
                ('sequence', models.IntegerField(help_text='Order of this stop in the trip (0-based)')),
                ('cumulative_miles', models.FloatField(default=0, help_text='Cumulative miles driven up to this stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Stop',
                'verbose_name_plural': 'Trip Stops',
                'ordering': ['trip', 'sequence'],
            },
        ),
    ]
